### ISSUE TITLE
schopenhauher

### ISSUE THREAD

**Issue by doktorbro** [linuxfreeordie/existentialcomics#3]
in the comic _[world cup philosophy](https://existentialcomics.com/comic/35)_ the name of schopenhauer in the first panel is wrong.

![worldcup-schopenhauher](https://user-images.githubusercontent.com/3617307/95018326-4b4e1400-065f-11eb-8722-5c92fca3ddf0.png)

**Comment by existentialcomics** [comment]
thanks, fixed
